### ISSUE TITLE
.Net Core Support

### ISSUE THREAD

**Issue by brad-ipcmobile** [square/connect-csharp-sdk#30]
I was wondering if you have a rough timeline for the .net core SDK.

**Comment by tristansokol** [comment]
There is no timeline for a .net core SDK. We use [Swagger-Codegen](https://github.com/swagger-api/swagger-codegen) for our client SDKs, so until there is a .net core client language available there, we will likely not have one for our SDKs.

**Comment by joeaudette** [comment]
getting ready to implement square in an asp.net core web app. Disappointing that I will have to fork this project or roll my own from scratch to get it working. Now I'm considering whether to use stripe instead since they already have support for asp.net core.

**Comment by joeaudette** [comment]
fyi for anyone else who needs support for asp.net core and can't wait around until there is official support, I have ported the code to netstandard2 and implemented a demo web app and successfully processed a charge using my sandbox credentials.

The code is here: https://github.com/joeaudette/square.netstandard

I've published a nuget package here: https://www.nuget.org/packages/Square.NetStandard/2.5.0

**Comment by tfsmag** [comment]
Thank you for doing this, your nuget package worked perfectly. I find it very odd that the official library STILL doesn't support dotnet core properly. You saved me a lot of work :) @joeaudette
